name: MacOS Desktop Build

on:
  push:
    branches: [ main ]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ main ]

jobs:
  build_macos_desktop:
    name: Build MacOS Desktop Binary
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Qt 6.10.3
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.10.3'
          target: 'desktop'
          arch: 'clang_64'
          dir: ${{ runner.temp }}/Qt
          install-deps: true
          tools: 'tools_ifw'

      - name: Configure CMake
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: |
          ls -lrt
          cmake --build build --parallel --config Release
          ls -lrt
          ls -lrt build
          ls -lrt build/dia_box.app

      - name: Install binary
        run: |
          cmake --install build --prefix build/install
          ls -lrt build/install

      - name: Deploy Qt dependencies with macdeployqt
        run: |
          ls -lrt
          macdeployqt build/install/dia_box.app -dmg -qmldir=.
          ls -lrt build/install

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-desktop-binary
          path: build/install/dia_box.app

      - name: Create GitHub release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: build/install/dia_box.app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
