name: MacOS Desktop Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_macos_desktop:
    name: Build MacOS Desktop Binary
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Qt 6.10.3
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.10.3'
          target: 'desktop'
          #arch: 'linux_gcc_64'
          dir: ${{ runner.temp }}/Qt
          install-deps: true
          tools: 'tools_ifw'

      - name: Configure CMake
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: |
          ls -lrt
          cmake --build build --parallel --config Release
          ls -lrt
          ls -lrt build
          ls -lrt build/DiaBox

      - name: Install binary
        run: cmake --install build --prefix build/install

      - name: Deploy Qt dependencies with macdeployqt
        run: |
          ls -lrt
          macdeployqt -dmg --release --qmldir . build/install/bin/dia_box.app
          ls -lrt build/install/bin

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-desktop-binary
          path: build/install/bin
