name: Windows Desktop Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_windows_desktop:
    name: Build Windows Desktop Binary
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Qt 6.9.3
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.9.3'
          target: 'desktop'
          arch: 'win64_msvc2019_64'
          dir: ${{ runner.temp }}/Qt
          install-deps: true

      #- name: Install build tools
      #  run: |
      #    sudo apt-get update
      #    sudo apt-get install -y cmake ninja-build

      - name: Configure CMake
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: |
          dir
          cmake --build build --parallel --config Release
          dir
          dir build
          dir build/x64
          dir build/x64/Release
          dir build/Release

      - name: Install binary
        run: cmake --install build --prefix build/install

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-desktop-binary
          path: build/install
